# -*- coding: utf-8 -*-
"""LAB 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p5yGYeAw9BkqPM7c7Q8Z6At-9dZxQPoa
"""

def printLatin(n):
  k = n + 1
  for i in range(1, n + 1):
    temp = k
    while (temp <= n):
      print(temp, end = " ")
      temp += 1
      
    for j in range(1, k):
      print(j, end = " ")
      
    k -= 1
    print()

print("LATIN SQUARE: \n")
n = int(input("Enter a number: "))
printLatin(n)

colors = ['Blue', 'Red', 'Green','Violet']

states = ['K', 'D', 'H', 'B2', 'B3', 'MB1','GR','SR',"LIB"]

neighbors = {}
neighbors['K'] = ['SR', 'D']
neighbors['D']=['B2','H','K','SR','MB1']
neighbors['H']=['D','B3']
neighbors['B2'] = ['D']
neighbors['B3'] = ['H']
neighbors['MB1'] = ['D', 'LIB']
neighbors['GR'] = []
neighbors['SR'] = ['K', 'LIB',]
neighbors['LIB']=['MB1','SR']

print("ROOM COLOURING PROBLEM:\n")
colors_of_states = {}

def promising(state, color):
    for neighbor in neighbors.get(state): 
        color_of_neighbor = colors_of_states.get(neighbor)
        if color_of_neighbor == color:
            return False

    return True

def get_color_for_state(state):
    for color in colors:
        if promising(state, color):
            return color

def main():
    for state in states:
        colors_of_states[state] = get_color_for_state(state)

    print(colors_of_states)


main()